name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  USER: briansterle

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build
      - name: Run tests
        run: go test
